# Generated by Django 5.1.5 on 2025-02-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orden',
            new_name='order',
        ),
    ]
